# This software was developed at the National Institute of Standards
# and Technology by employees of the Federal Government in the course
# of their official duties. Pursuant to title 17 Section 105 of the
# United States Code this software is not subject to copyright
# protection and is in the public domain. NIST assumes no
# responsibility whatsoever for its use by other parties, and makes
# no guarantees, expressed or implied, about its quality,
# reliability, or any other characteristic.
#
# We would appreciate acknowledgement if the software is used.

SELECT ?lEvaluationType ?lEvidenceEvaluation ?lEvaluationRationale ?lConclusion
WHERE {
#  ?nAnalysisAction
#    a drafting:AnalysisAction ;
#    uco-core:hasFacet/uco-action:object ?nHypothesis ;
#    uco-core:hasFacet/uco-action:result ?nAnalyticResult ;
#    .

  ?nAnalyticResult
    a drafting:AnalyticResult ;
    uco-core:hasFacet ?nHypothesisTestResultFacet ;
    .

  ?nHypothesisTestResultFacet
    a drafting:HypothesisTestResultFacet ;
    drafting:evaluationRationale ?lEvaluationRationale ;
    drafting:evaluationType ?lEvaluationType ;
    drafting:conclusion ?lConclusion ;
    drafting:evidenceEvaluation ?lEvidenceEvaluation ;
    .

#  ?nHypothesis
#    a drafting:Hypothesis ;
#    uco-core:statement ?lStatement ;
#    .
}
# Note - the IRIs' UUID components were picked to sort in a desired presentation order.
ORDER BY ?nHypothesisTestResultFacet
