# This software was developed at the National Institute of Standards
# and Technology by employees of the Federal Government in the course
# of their official duties. Pursuant to title 17 Section 105 of the
# United States Code this software is not subject to copyright
# protection and is in the public domain. NIST assumes no
# responsibility whatsoever for its use by other parties, and makes
# no guarantees, expressed or implied, about its quality,
# reliability, or any other characteristic.
#
# We would appreciate acknowledgement if the software is used.

SELECT ?nBasisObject ?lSupports
WHERE {
  {
    SELECT ?nBasisObject ?lSupports
    WHERE {
      kb:analysisaction-B615357B-F1B5-40B0-BA97-368DC6C817B9
        uco-action:object ?nBasisObject ;
        .
      FILTER NOT EXISTS {
        kb:analysisaction-242CBB2B-9DCB-451B-994F-E70770F1BC50
          uco-action:object ?nBasisObject ;
          .
      }
      BIND ("A" AS ?lSupports)
    }
  }
  UNION
  {
    SELECT ?nBasisObject ?lSupports
    WHERE {
      kb:analysisaction-242CBB2B-9DCB-451B-994F-E70770F1BC50
        uco-action:object ?nBasisObject ;
        .
      FILTER NOT EXISTS {
        kb:analysisaction-B615357B-F1B5-40B0-BA97-368DC6C817B9
          uco-action:object ?nBasisObject ;
          .
      }
      BIND ("B" AS ?lSupports)
    }
  }
  UNION
  {
    SELECT ?nBasisObject ?lSupports
    WHERE {
      kb:analysisaction-B615357B-F1B5-40B0-BA97-368DC6C817B9
        uco-action:object ?nBasisObject ;
        .
      kb:analysisaction-242CBB2B-9DCB-451B-994F-E70770F1BC50
        uco-action:object ?nBasisObject ;
        .
      BIND ("both" AS ?lSupports)
    }
  }
}
ORDER BY ?lSupports ?nBasisObject
