# Find all mobile device operating system fingerprints, and the devices in the knowledge graph bearing them.
SELECT ?nDevice ?lAdvertisingID
WHERE {
  ?nDevice
    a/rdfs:subClassOf* uco-observable:Device ;
    uco-core:hasFacet ?nSpecializedMobileDeviceFacet ;
    .

  ?nSpecializedMobileDeviceFacet
    ?pAdvertisingID ?lAdvertisingID ;
    .

  ?pAdvertisingID rdfs:subPropertyOf* drafting:advertisingID .
}
ORDER BY ?nDevice ?lAdvertisingID
