PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX case-investigation: <https://ontology.caseontology.org/case/investigation/>
PREFIX uco-core: <https://ontology.unifiedcyberontology.org/uco/core/>
SELECT ?nInvestigation ?lName ?lDescription
WHERE {
  ?nInvestigation
    a/rdfs:subClassOf* case-investigation:Investigation ;
    .
  OPTIONAL {
    ?nInvestigation
      uco-core:name ?lName ;
      .
  }
  OPTIONAL {
    ?nInvestigation
      uco-core:description ?lDescription ;
      .
  }
}
ORDER BY ?lName
